### ISSUE TITLE
CC1101 compatible with LoRa?

### ISSUE THREAD

**Issue by Lutzion** [mrfaptastic/Easy-IoT-Arduino-CC1101#10]
Hello mrfaptastic,

on this site [https://forum.flipperzero.one/t/433-only-or-full-300-928-mhz-band/384/2](https://forum.flipperzero.one/t/433-only-or-full-300-928-mhz-band/384/2) there is a discussion, if you managed to make CC1101 compatible with LoRa as the name of this project lets assume so.
As LoRa modulation is different from CC1101s modulation i dont think so. 
Is this library compatible with LoRa so that CC1101 can talk to a SX1276 module?

**Comment by mrfaptastic** [comment]
Hello. I've removed the reference to LORA in the git name. I can't remember why that was part of the original name.

Ther different incompatable chips / rf modulation types as far as I'm aware.
