### ISSUE TITLE
sending packet to arduino from ESP32 but not reciving 

### ISSUE THREAD

**Issue by MakGyv3r** [mrfaptastic/Easy-IoT-Arduino-CC1101#8]
hi @mrfaptastic, 

I tried sending a packet to Arduino from esp32 but it didn't get it.
I used [SpaceTeddy](https://github.com/SpaceTeddy/CC1101/blob/master/examples/Arduino/Rx_demo/Rx_demo.ino) library and I did some changes to suit your library I attached the changed library [EOTAUpdate-master.zip](https://github.com/mrfaptastic/Easy-IoT-Arduino-CC1101-LORA/files/6092449/EOTAUpdate-master.zip) and also [my code for the arduino](https://github.com/mrfaptastic/Easy-IoT-Arduino-CC1101-LORA/files/6092538/arduino_cc1101.zip) and my code for the [esp32](https://github.com/mrfaptastic/Easy-IoT-Arduino-CC1101-LORA/files/6092557/CC1101_tx_full.zip). 
but I didn't succeed in receiving the packet by the Arduino, maybe you can help me.

**Comment by mrfaptastic** [comment]
You'll need to use the same library on both ends I think. So try using SpaceTeddy's on the ESP32 as well.

**Comment by mrfaptastic** [comment]
I've updated this library so if you use it on both sides it should work OK.
